[profile.default]
solc_version = "0.8.20"
via_ir = true
optimizer = true
optimizer_runs = 200
src = "src"
out = "out"
ffi = true
ast = true
build_info = true

test = "test"

libs = [
    "lib",
    "node_modules",
]
remappings = [
  "ds-test/=lib/forge-std/lib/ds-test/src/",
  "forge-std/=lib/forge-std/src/",
  "@openzeppelin/contracts/=lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts/",
  "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
  "@modules/=src/modules/",
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config