[features]
seeds = false
skip-lint = false

[workspace]
members = [
    "programs/relayer",
]

[programs.localnet]
relayer = "GSS2BQQYmXSDkB25bwaumRMsaWJNDu18UzUByCWf1NaL"

[programs.devnet]
relayer = "GSS2BQQYmXSDkB25bwaumRMsaWJNDu18UzUByCWf1NaL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
# cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 ts/tests/*.ts"

[test]
startup_wait = 10000

[test.validator]
url = "https://api.mainnet-beta.solana.com"

### MPL Token Metadata
[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"

### Wormhole Core Bridge
[[test.validator.clone]]
address = "worm2ZoG2kUd4vFXhvjh93UUH596ayRfgQ2MgjNMTth"

### Wormhole Token Bridge
[[test.validator.clone]]
address = "wormDTUJ6AWPNvk59vGQbDvGJmqbDTdgWgAqcLBCgUb"
